import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'hi', 'es', 'fr', 'de', 'zh_Hans', 'ja', 'ru', 'ar', 'pt'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? hiText = '',
    String? esText = '',
    String? frText = '',
    String? deText = '',
    String? zh_HansText = '',
    String? jaText = '',
    String? ruText = '',
    String? arText = '',
    String? ptText = '',
  }) =>
      [
        enText,
        hiText,
        esText,
        frText,
        deText,
        zh_HansText,
        jaText,
        ruText,
        arText,
        ptText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'n3o09m26': {
      'en': 'Tap Here',
      'ar': 'انقر هنا',
      'de': 'Tippen Sie hier',
      'es': 'Toque aquí',
      'fr': 'Appuyez ici',
      'hi': 'यहां टैप करें',
      'ja': 'ここをタップ',
      'pt': 'Toque aqui',
      'ru': 'Нажмите здесь',
      'zh_Hans': '点击此处',
    },
    'nkrpzgi3': {
      'en': 'Object Detector',
      'ar': 'كاشف الأشياء',
      'de': 'Objektdetektor',
      'es': 'Detector de objetos',
      'fr': 'Détecteur d\'objets',
      'hi': 'ऑब्जेक्ट डिटेक्टर',
      'ja': 'オブジェクト検出器',
      'pt': 'Detector de objetos',
      'ru': 'Детектор объектов',
      'zh_Hans': '物体探测器',
    },
    'm06svl5n': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'होम',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
    'htvwkkn2': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'होम',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // LoginPage
  {
    'jvzeoge2': {
      'en': 'ThirdEye',
      'ar': 'العين الثالثة',
      'de': 'Drittes Auge',
      'es': 'Tercer Ojo',
      'fr': 'Troisième œil',
      'hi': 'तीसरी आंख',
      'ja': 'サードアイ',
      'pt': 'Terceiro Olho',
      'ru': 'Третий глаз',
      'zh_Hans': '第三只眼',
    },
    'r2wvc1zc': {
      'en': 'Sign In',
      'ar': 'تسجيل الدخول',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'hi': 'दाखिल करना',
      'ja': 'サインイン',
      'pt': 'Entrar',
      'ru': 'Войти',
      'zh_Hans': '登入',
    },
    'kb4wo62e': {
      'en': 'Let\'s get started by filling out the form below.',
      'ar': 'لنبدأ بملء النموذج أدناه.',
      'de': 'Beginnen wir, indem Sie das folgende Formular ausfüllen.',
      'es': 'Comencemos rellenando el formulario a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'hi': 'आइये नीचे दिया गया फॉर्म भरकर शुरुआत करें।',
      'ja': 'まずは以下のフォームに記入しましょう。',
      'pt': 'Vamos começar preenchendo o formulário abaixo.',
      'ru': 'Давайте начнем с заполнения формы ниже.',
      'zh_Hans': '让我们从填写下面的表格开始。',
    },
    '4ciydwja': {
      'en': 'Email',
      'ar': 'بريد إلكتروني',
      'de': 'E-Mail',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'ja': 'メール',
      'pt': 'E-mail',
      'ru': 'Электронная почта',
      'zh_Hans': '电子邮件',
    },
    'kmwkn7a0': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'pt': 'Senha',
      'ru': 'Пароль',
      'zh_Hans': '密码',
    },
    'k313lo6y': {
      'en': 'Sign In',
      'ar': 'تسجيل الدخول',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'hi': 'दाखिल करना',
      'ja': 'サインイン',
      'pt': 'Entrar',
      'ru': 'Войти',
      'zh_Hans': '登入',
    },
    'dj9i7xm9': {
      'en': 'Or sign up with',
      'ar': 'أو قم بالتسجيل مع',
      'de': 'Oder registrieren Sie sich mit',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'hi': 'या साइन अप करें',
      'ja': 'またはサインアップ',
      'pt': 'Ou inscreva-se com',
      'ru': 'Или зарегистрируйтесь с помощью',
      'zh_Hans': '或注册',
    },
    'fbw8gqj2': {
      'en': 'Continue with Google',
      'ar': 'متابعة مع جوجل',
      'de': 'Weiter mit Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'hi': 'Google के साथ जारी रखें',
      'ja': 'Googleで続行',
      'pt': 'Continuar com o Google',
      'ru': 'Продолжить с Google',
      'zh_Hans': '继续使用 Google',
    },
    'y6zvx0hk': {
      'en': 'Continue with Apple',
      'ar': 'متابعة مع Apple',
      'de': 'Weiter mit Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'hi': 'एप्पल के साथ जारी रखें',
      'ja': 'Appleで続ける',
      'pt': 'Continuar com a Apple',
      'ru': 'Продолжить с Apple',
      'zh_Hans': '继续使用 Apple',
    },
    'b7ykoden': {
      'en': 'please enter valid email',
      'ar': 'الرجاء إدخال بريد إلكتروني صالح',
      'de': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
      'es': 'Por favor ingrese un correo electrónico válido',
      'fr': 'veuillez entrer une adresse e-mail valide',
      'hi': 'कृपया वैध ईमेल दर्ज करें',
      'ja': '有効なメールアドレスを入力してください',
      'pt': 'por favor insira um e-mail válido',
      'ru': 'пожалуйста, введите действительный адрес электронной почты',
      'zh_Hans': '请输入有效的电子邮件',
    },
    'wpx3waht': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'tglgt8ih': {
      'en': 'field is required',
      'ar': 'الحقل مطلوب',
      'de': 'Feld ist erforderlich',
      'es': 'El campo es obligatorio',
      'fr': 'le champ est obligatoire',
      'hi': 'ये स्थान भरा जाना है',
      'ja': 'フィールドは必須です',
      'pt': 'campo é obrigatório',
      'ru': 'поле обязательно',
      'zh_Hans': '必填字段',
    },
    'bhpi9e45': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'tq8kgpld': {
      'en': 'Sign Up',
      'ar': 'اشتراك',
      'de': 'Melden Sie sich an',
      'es': 'Inscribirse',
      'fr': 'S\'inscrire',
      'hi': 'साइन अप करें',
      'ja': 'サインアップ',
      'pt': 'Inscrever-se',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '报名',
    },
    'sblr0991': {
      'en': 'Let\'s get started by filling out the form below.',
      'ar': 'لنبدأ بملء النموذج أدناه.',
      'de': 'Beginnen wir, indem Sie das folgende Formular ausfüllen.',
      'es': 'Comencemos rellenando el formulario a continuación.',
      'fr': 'Commençons par remplir le formulaire ci-dessous.',
      'hi': 'आइये नीचे दिया गया फॉर्म भरकर शुरुआत करें।',
      'ja': 'まずは以下のフォームに記入しましょう。',
      'pt': 'Vamos começar preenchendo o formulário abaixo.',
      'ru': 'Давайте начнем с заполнения формы ниже.',
      'zh_Hans': '让我们从填写下面的表格开始。',
    },
    'q6b1wx6b': {
      'en': 'Name',
      'ar': 'اسم',
      'de': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'hi': 'नाम',
      'ja': '名前',
      'pt': 'Nome',
      'ru': 'Имя',
      'zh_Hans': '姓名',
    },
    'ysb8qg3v': {
      'en': 'Email',
      'ar': 'بريد إلكتروني',
      'de': 'E-Mail',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'ja': 'メール',
      'pt': 'E-mail',
      'ru': 'Электронная почта',
      'zh_Hans': '电子邮件',
    },
    'k6smrpng': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'pt': 'Senha',
      'ru': 'Пароль',
      'zh_Hans': '密码',
    },
    'wv3ogu7o': {
      'en': 'Confirm Password',
      'ar': 'تأكيد كلمة المرور',
      'de': 'Passwort bestätigen',
      'es': 'confirmar Contraseña',
      'fr': 'Confirmez le mot de passe',
      'hi': 'पासवर्ड की पुष्टि कीजिये',
      'ja': 'パスワードを認証する',
      'pt': 'Confirme sua senha',
      'ru': 'Подтвердите пароль',
      'zh_Hans': '确认密码',
    },
    'klq4kgrl': {
      'en': 'Create Account',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'ja': 'アカウントを作成する',
      'pt': 'Criar uma conta',
      'ru': 'Зарегистрироваться',
      'zh_Hans': '创建账户',
    },
    'lvo1gv4s': {
      'en': 'Or sign up with',
      'ar': 'أو قم بالتسجيل مع',
      'de': 'Oder registrieren Sie sich mit',
      'es': 'O regístrate con',
      'fr': 'Ou inscrivez-vous avec',
      'hi': 'या साइन अप करें',
      'ja': 'またはサインアップ',
      'pt': 'Ou inscreva-se com',
      'ru': 'Или зарегистрируйтесь с помощью',
      'zh_Hans': '或注册',
    },
    'dchl15sy': {
      'en': 'Continue with Google',
      'ar': 'متابعة مع جوجل',
      'de': 'Weiter mit Google',
      'es': 'Continuar con Google',
      'fr': 'Continuer avec Google',
      'hi': 'Google के साथ जारी रखें',
      'ja': 'Googleで続行',
      'pt': 'Continuar com o Google',
      'ru': 'Продолжить с Google',
      'zh_Hans': '继续使用 Google',
    },
    'f22pmish': {
      'en': 'Continue with Apple',
      'ar': 'متابعة مع Apple',
      'de': 'Weiter mit Apple',
      'es': 'Continuar con Apple',
      'fr': 'Continuer avec Apple',
      'hi': 'एप्पल के साथ जारी रखें',
      'ja': 'Appleで続ける',
      'pt': 'Continuar com a Apple',
      'ru': 'Продолжить с Apple',
      'zh_Hans': '继续使用 Apple',
    },
    's7zdbsx8': {
      'en': 'field is required',
      'ar': 'الحقل مطلوب',
      'de': 'Feld ist erforderlich',
      'es': 'El campo es obligatorio',
      'fr': 'le champ est obligatoire',
      'hi': 'ये स्थान भरा जाना है',
      'ja': 'フィールドは必須です',
      'pt': 'campo é obrigatório',
      'ru': 'поле обязательно',
      'zh_Hans': '必填字段',
    },
    'jzefaru0': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    't48fbjjf': {
      'en': 'please enter valid email',
      'ar': 'الرجاء إدخال بريد إلكتروني صالح',
      'de': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
      'es': 'Por favor ingrese un correo electrónico válido',
      'fr': 'veuillez entrer une adresse e-mail valide',
      'hi': 'कृपया वैध ईमेल दर्ज करें',
      'ja': '有効なメールアドレスを入力してください',
      'pt': 'por favor insira um e-mail válido',
      'ru': 'пожалуйста, введите действительный адрес электронной почты',
      'zh_Hans': '请输入有效的电子邮件',
    },
    '3e7s1ydf': {
      'en': 'Please enter valid email',
      'ar': 'الرجاء إدخال بريد إلكتروني صالح',
      'de': 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
      'es': 'Por favor ingrese un correo electrónico válido',
      'fr': 'Veuillez entrer une adresse e-mail valide',
      'hi': 'कृपया मान्य ईमेल दर्ज करें',
      'ja': '有効なメールアドレスを入力してください',
      'pt': 'Por favor, insira um e-mail válido',
      'ru': 'Пожалуйста, введите действительный адрес электронной почты',
      'zh_Hans': '请输入有效的电子邮箱',
    },
    '6okf46c1': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'luj467om': {
      'en': 'field is required',
      'ar': 'الحقل مطلوب',
      'de': 'Feld ist erforderlich',
      'es': 'El campo es obligatorio',
      'fr': 'le champ est obligatoire',
      'hi': 'ये स्थान भरा जाना है',
      'ja': 'フィールドは必須です',
      'pt': 'campo é obrigatório',
      'ru': 'поле обязательно',
      'zh_Hans': '必填字段',
    },
    '70rjpu91': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'a42lqe1p': {
      'en': 'field is required',
      'ar': 'الحقل مطلوب',
      'de': 'Feld ist erforderlich',
      'es': 'El campo es obligatorio',
      'fr': 'le champ est obligatoire',
      'hi': 'ये स्थान भरा जाना है',
      'ja': 'フィールドは必須です',
      'pt': 'campo é obrigatório',
      'ru': 'поле обязательно',
      'zh_Hans': '必填字段',
    },
    '3zi0ul1v': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'k4uml2yh': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // EmergencyContactlPage
  {
    'b96yeq1v': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'zezcasee': {
      'en': 'Emergency Contacts',
      'ar': 'جهات الاتصال في حالات الطوارئ',
      'de': 'Notfallkontakte',
      'es': 'Contactos de emergencia',
      'fr': 'Contacts d\'urgence',
      'hi': 'आपातकालीन संपर्क',
      'ja': '緊急連絡先',
      'pt': 'Contatos de emergência',
      'ru': 'Контакты для экстренных случаев',
      'zh_Hans': '紧急联系方式',
    },
    'mqiewh1i': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // LanguagePage
  {
    'sve8xso5': {
      'en': 'Language',
      'ar': 'لغة',
      'de': 'Sprache',
      'es': 'Idioma',
      'fr': 'Langue',
      'hi': 'भाषा',
      'ja': '言語',
      'pt': 'Linguagem',
      'ru': 'Язык',
      'zh_Hans': '语言',
    },
    'mg75423i': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'hi': 'बचाना',
      'ja': '保存',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'zh_Hans': '节省',
    },
    'jmvdxu70': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // InfoPage
  {
    '5r44vlcg': {
      'en': 'How to use this app ?',
      'ar': 'كيفية استخدام هذا التطبيق؟',
      'de': 'Wie verwende ich diese App?',
      'es': '¿Cómo utilizar esta aplicación?',
      'fr': 'Comment utiliser cette application ?',
      'hi': 'इस ऐप का उपयोग कैसे करें?',
      'ja': 'このアプリの使い方は？',
      'pt': 'Como usar este aplicativo?',
      'ru': 'Как пользоваться этим приложением?',
      'zh_Hans': '如何使用这个应用程序？',
    },
    'i56pci1q': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // EntryPage
  {
    'ipuxrq6u': {
      'en': 'What’s Around Me',
      'ar': 'ما هو حولي',
      'de': 'Was ist um mich herum',
      'es': '¿Qué hay a mi alrededor?',
      'fr': 'Ce qui m\'entoure',
      'hi': 'मेरे आस-पास क्या है?',
      'ja': '私の周りにあるもの',
      'pt': 'O que está ao meu redor',
      'ru': 'Что вокруг меня',
      'zh_Hans': '我周围有什么',
    },
    'yzs483j2': {
      'en':
          'Captures a 5-second video and provides an audio description of the surroundings.',
      'ar': 'يلتقط مقطع فيديو مدته 5 ثوانٍ ويقدم وصفًا صوتيًا للمحيط.',
      'de':
          'Nimmt ein 5-Sekunden-Video auf und bietet eine Audiobeschreibung der Umgebung.',
      'es':
          'Captura un video de 5 segundos y proporciona una descripción de audio del entorno.',
      'fr':
          'Capture une vidéo de 5 secondes et fournit une description audio de l\'environnement.',
      'hi':
          '5 सेकंड का वीडियो कैप्चर करता है और आसपास के वातावरण का ऑडियो विवरण प्रदान करता है।',
      'ja': '5 秒間のビデオをキャプチャし、周囲の音声による説明を提供します。',
      'pt':
          'Captura um vídeo de 5 segundos e fornece uma descrição em áudio do ambiente.',
      'ru':
          'Записывает 5-секундное видео и предоставляет аудиоописание окружающей обстановки.',
      'zh_Hans': '捕捉 5 秒视频并提供周围环境的音频描述。',
    },
    '909a443p': {
      'en': 'Skip',
      'ar': 'يتخطى',
      'de': 'Überspringen',
      'es': 'Saltar',
      'fr': 'Sauter',
      'hi': 'छोडना',
      'ja': 'スキップ',
      'pt': 'Pular',
      'ru': 'Пропускать',
      'zh_Hans': '跳过',
    },
    '19erh7mk': {
      'en': 'Emergency Alert to Contacts',
      'ar': 'تنبيه الطوارئ إلى جهات الاتصال',
      'de': 'Notfallalarm an Kontakte',
      'es': 'Alerta de emergencia a contactos',
      'fr': 'Alerte d\'urgence aux contacts',
      'hi': 'संपर्कों को आपातकालीन चेतावनी',
      'ja': '連絡先への緊急警報',
      'pt': 'Alerta de emergência para contatos',
      'ru': 'Экстренное оповещение контактов',
      'zh_Hans': '向联系人发出紧急警报',
    },
    '7vztcfdq': {
      'en':
          'Sends an emergency message to selected contacts for immediate assistance.',
      'ar':
          'إرسال رسالة طوارئ إلى جهات اتصال محددة للحصول على المساعدة الفورية.',
      'de':
          'Sendet eine Notfallnachricht an ausgewählte Kontakte, um sofortige Hilfe zu erhalten.',
      'es':
          'Envía un mensaje de emergencia a contactos seleccionados para asistencia inmediata.',
      'fr':
          'Envoie un message d\'urgence aux contacts sélectionnés pour une assistance immédiate.',
      'hi': 'तत्काल सहायता के लिए चयनित संपर्कों को आपातकालीन संदेश भेजता है।',
      'ja': 'すぐに支援を受けるために、選択した連絡先に緊急メッセージを送信します。',
      'pt':
          'Envia uma mensagem de emergência para contatos selecionados para assistência imediata.',
      'ru':
          'Отправляет экстренное сообщение выбранным контактам для немедленной помощи.',
      'zh_Hans': '向选定的联系人发送紧急消息以获得立即援助。',
    },
    'sycmhc3o': {
      'en': 'Skip',
      'ar': 'يتخطى',
      'de': 'Überspringen',
      'es': 'Saltar',
      'fr': 'Sauter',
      'hi': 'छोडना',
      'ja': 'スキップ',
      'pt': 'Pular',
      'ru': 'Пропускать',
      'zh_Hans': '跳过',
    },
    'mbpf06rf': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // RecordingPage
  {
    '78d5eqmw': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // ListenRecordingPage
  {
    'wothnnea': {
      'en': 'Please hold on while we transform your video into audio',
      'ar': 'يرجى الانتظار بينما نقوم بتحويل الفيديو الخاص بك إلى صوت',
      'de': 'Bitte warten Sie, während wir Ihr Video in Audio umwandeln',
      'es': 'Por favor, espere mientras transformamos su video en audio.',
      'fr':
          'Veuillez patienter pendant que nous transformons votre vidéo en audio',
      'hi':
          'कृपया तब तक प्रतीक्षा करें जब तक हम आपके वीडियो को ऑडियो में परिवर्तित नहीं कर देते',
      'ja': 'ビデオを音声に変換するまでしばらくお待ちください',
      'pt': 'Aguarde enquanto transformamos seu vídeo em áudio',
      'ru': 'Пожалуйста, подождите, пока мы преобразуем ваше видео в аудио.',
      'zh_Hans': '请稍候，我们正在将您的视频转换为音频',
    },
    'taiori1z': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'eebnqjqd': {
      'en': 'Processing',
      'ar': 'يعالج',
      'de': 'Verarbeitung',
      'es': 'Tratamiento',
      'fr': 'Traitement',
      'hi': 'प्रसंस्करण',
      'ja': '処理',
      'pt': 'Processamento',
      'ru': 'Обработка',
      'zh_Hans': '加工',
    },
    'osmles7e': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // ObjectDetectorPage
  {
    'y9dypqy0': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // OnboardingPage
  {
    'zyaymd99': {
      'en': 'ThirdEye',
      'ar': 'العين الثالثة',
      'de': 'Drittes Auge',
      'es': 'Tercer Ojo',
      'fr': 'Troisième œil',
      'hi': 'तीसरी आंख',
      'ja': 'サードアイ',
      'pt': 'Terceiro Olho',
      'ru': 'Третий глаз',
      'zh_Hans': '第三只眼',
    },
    '9x0hd73d': {
      'en': 'Get Started',
      'ar': 'البدء',
      'de': 'Erste Schritte',
      'es': 'Empezar',
      'fr': 'Commencer',
      'hi': 'शुरू हो जाओ',
      'ja': '始める',
      'pt': 'Começar',
      'ru': 'Начать',
      'zh_Hans': '立即开始',
    },
    'sup64u8r': {
      'en': 'Already a member?  ',
      'ar': 'هل أنت عضو بالفعل؟',
      'de': 'Bereits Mitglied?',
      'es': '¿Ya eres miembro?',
      'fr': 'Déjà membre ?',
      'hi': 'क्या पहले से ही सदस्य हैं?',
      'ja': 'すでに会員ですか?',
      'pt': 'Já é membro?',
      'ru': 'Вы уже являетесь участником?',
      'zh_Hans': '已经是会员？',
    },
    'n2a3t28a': {
      'en': 'Sign In',
      'ar': 'تسجيل الدخول',
      'de': 'Anmelden',
      'es': 'Iniciar sesión',
      'fr': 'Se connecter',
      'hi': 'दाखिल करना',
      'ja': 'サインイン',
      'pt': 'Entrar',
      'ru': 'Войти',
      'zh_Hans': '登入',
    },
    'pws9bvup': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // ContactPersonPage
  {
    '7ibxwyvc': {
      'en': 'Contact info',
      'ar': 'معلومات الاتصال',
      'de': 'Kontaktinformationen',
      'es': 'Información de contacto',
      'fr': 'Coordonnées',
      'hi': 'संपर्क सूचना',
      'ja': '連絡先情報',
      'pt': 'Informações de contato',
      'ru': 'Контактная информация',
      'zh_Hans': '联系方式',
    },
    'beboar4f': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
  },
  // TestPage
  {
    'essmq43m': {
      'en': 'Page Title',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '0jsmjqkk': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // menu_left_drawer
  {
    'lje5f0kl': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'होम',
      'ja': '家',
      'pt': 'Lar',
      'ru': 'Дом',
      'zh_Hans': '家',
    },
    'jf91om2y': {
      'en': 'Emergency Contacts',
      'ar': 'جهات الاتصال في حالات الطوارئ',
      'de': 'Notfallkontakte',
      'es': 'Contactos de emergencia',
      'fr': 'Contacts d\'urgence',
      'hi': 'आपातकालीन संपर्क',
      'ja': '緊急連絡先',
      'pt': 'Contatos de emergência',
      'ru': 'Контакты для экстренных случаев',
      'zh_Hans': '紧急联系方式',
    },
    '513f0l3e': {
      'en': 'Language',
      'ar': 'لغة',
      'de': 'Sprache',
      'es': 'Idioma',
      'fr': 'Langue',
      'hi': 'भाषा',
      'ja': '言語',
      'pt': 'Linguagem',
      'ru': 'Язык',
      'zh_Hans': '语言',
    },
    'u5yj3dzo': {
      'en': 'How to use this app ?',
      'ar': 'كيفية استخدام هذا التطبيق؟',
      'de': 'Wie verwende ich diese App?',
      'es': '¿Cómo utilizar esta aplicación?',
      'fr': 'Comment utiliser cette application ?',
      'hi': 'इस ऐप का उपयोग कैसे करें?',
      'ja': 'このアプリの使い方は？',
      'pt': 'Como usar este aplicativo?',
      'ru': 'Как пользоваться этим приложением?',
      'zh_Hans': '如何使用这个应用程序？',
    },
    'xhzp6zzg': {
      'en': 'Log out',
      'ar': 'تسجيل الخروج',
      'de': 'Aus Konto abmelden',
      'es': 'Finalizar la sesión',
      'fr': 'Se déconnecter',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'pt': 'Sair',
      'ru': 'Выйти',
      'zh_Hans': '登出',
    },
  },
  // add_contact
  {
    'app5jrrm': {
      'en': 'Contact person Name',
      'ar': 'اسم جهة الاتصال',
      'de': 'Ansprechpartner Name',
      'es': 'Persona de contacto Nombre',
      'fr': 'Personne à contacter Nom',
      'hi': 'संपर्क व्यक्ति का नाम',
      'ja': '担当者名',
      'pt': 'Nome da pessoa de contato',
      'ru': 'Контактное лицо Имя',
      'zh_Hans': '联系人姓名',
    },
    '6y8vewek': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'h59juv4u': {
      'en': 'Enter Name',
      'ar': 'أدخل الاسم',
      'de': 'Namen eingeben',
      'es': 'Introducir nombre',
      'fr': 'Entrez le nom',
      'hi': 'नाम दर्ज करें',
      'ja': '名前を入力',
      'pt': 'Digite o nome',
      'ru': 'Введите имя',
      'zh_Hans': '输入姓名',
    },
    'xfztxwaz': {
      'en': 'Please enter name.',
      'ar': 'الرجاء إدخال الاسم.',
      'de': 'Bitte geben Sie den Namen ein.',
      'es': 'Por favor, introduzca el nombre.',
      'fr': 'Veuillez entrer un nom.',
      'hi': 'कृपया नाम दर्ज करें.',
      'ja': '名前を入力してください。',
      'pt': 'Por favor, insira o nome.',
      'ru': 'Введите имя.',
      'zh_Hans': '请输入姓名。',
    },
    'idj4tu8i': {
      'en': ' Email Id',
      'ar': 'معرف البريد الإلكتروني',
      'de': 'E-Mail-ID',
      'es': 'Identificación de correo electrónico',
      'fr': 'Identifiant de courrier électronique',
      'hi': 'ईमेल आईडी',
      'ja': 'メールID',
      'pt': 'ID de e-mail',
      'ru': 'Идентификатор электронной почты',
      'zh_Hans': '電子郵件',
    },
    '4qz6luuh': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'zv68ye9v': {
      'en': 'Enter Email',
      'ar': 'أدخل البريد الإلكتروني',
      'de': 'E-Mail eingeben',
      'es': 'Introducir correo electrónico',
      'fr': 'Entrez votre adresse e-mail',
      'hi': 'ईमेल दर्ज करें',
      'ja': 'メールアドレスを入力',
      'pt': 'Digite o e-mail',
      'ru': 'Введите адрес электронной почты',
      'zh_Hans': '输入电子邮箱',
    },
    'qrwlbvus': {
      'en': 'Please enter email id.',
      'ar': 'الرجاء إدخال معرف البريد الإلكتروني.',
      'de': 'Bitte geben Sie Ihre E-Mail-ID ein.',
      'es': 'Por favor, introduzca su dirección de correo electrónico.',
      'fr': 'Veuillez entrer votre identifiant e-mail.',
      'hi': 'कृपया ईमेल आईडी दर्ज करें.',
      'ja': 'メールIDを入力してください。',
      'pt': 'Por favor, insira o ID de e-mail.',
      'ru': 'Введите адрес электронной почты.',
      'zh_Hans': '请输入电子邮件 ID。',
    },
    'v36c4ygp': {
      'en': 'Contact Number',
      'ar': 'رقم التواصل',
      'de': 'Kontaktnummer',
      'es': 'Número de contacto',
      'fr': 'Numéro de contact',
      'hi': 'संपर्क संख्या',
      'ja': '連絡先',
      'pt': 'Número de contato',
      'ru': 'Контактный номер',
      'zh_Hans': '联系电话',
    },
    's3ndl4ge': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '48zudnw5': {
      'en': 'Enter Mobile Number',
      'ar': 'أدخل رقم الهاتف المحمول',
      'de': 'Geben Sie die Mobilnummer ein',
      'es': 'Introducir número de móvil',
      'fr': 'Entrez le numéro de portable',
      'hi': 'मोबाइल नंबर दर्ज करें',
      'ja': '携帯電話番号を入力してください',
      'pt': 'Digite o número do celular',
      'ru': 'Введите номер мобильного телефона',
      'zh_Hans': '输入手机号码',
    },
    '9odbj1sk': {
      'en': 'Please enter contact number.',
      'ar': 'الرجاء إدخال رقم التواصل.',
      'de': 'Bitte geben Sie die Kontaktnummer ein.',
      'es': 'Por favor, introduzca el número de contacto.',
      'fr': 'Veuillez entrer le numéro de contact.',
      'hi': 'कृपया संपर्क नंबर दर्ज करें.',
      'ja': '連絡先番号を入力してください。',
      'pt': 'Por favor, insira o número de contato.',
      'ru': 'Введите контактный номер.',
      'zh_Hans': '请输入联系电话。',
    },
    '45xk33vn': {
      'en': 'Save',
      'ar': 'يحفظ',
      'de': 'Speichern',
      'es': 'Ahorrar',
      'fr': 'Sauvegarder',
      'hi': 'बचाना',
      'ja': '保存',
      'pt': 'Salvar',
      'ru': 'Сохранять',
      'zh_Hans': '节省',
    },
    'wi97lomo': {
      'en': 'field is required',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'xhxmyrwo': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '7i44x8ui': {
      'en': 'please enter valid email',
      'ar': 'الحقل مطلوب',
      'de': 'Feld ist erforderlich',
      'es': 'El campo es obligatorio',
      'fr': 'le champ est obligatoire',
      'hi': 'ये स्थान भरा जाना है',
      'ja': 'フィールドは必須です',
      'pt': 'campo é obrigatório',
      'ru': 'поле обязательно',
      'zh_Hans': '必填字段',
    },
    'a5qf3rdg': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'xt08vjhf': {
      'en': 'please enter valid mobile number',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '9m94yfmb': {
      'en': 'Please choose an option from the dropdown',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
  // delete_contact
  {
    'mgc0ihr0': {
      'en': 'Do you want to delete this contact ?',
      'ar': 'هل تريد حذف هذه جهة الاتصال؟',
      'de': 'Möchten Sie diesen Kontakt löschen?',
      'es': '¿Quieres eliminar este contacto?',
      'fr': 'Voulez-vous supprimer ce contact ?',
      'hi': 'क्या आप इस संपर्क को हटाना चाहते हैं?',
      'ja': 'この連絡先を削除しますか?',
      'pt': 'Você quer apagar este contato?',
      'ru': 'Вы хотите удалить этот контакт?',
      'zh_Hans': '您要删除此联系人吗？',
    },
    's4gcjq7r': {
      'en': 'No',
      'ar': 'لا',
      'de': 'NEIN',
      'es': 'No',
      'fr': 'Non',
      'hi': 'नहीं',
      'ja': 'いいえ',
      'pt': 'Não',
      'ru': 'Нет',
      'zh_Hans': '不',
    },
    'oo6vsb5t': {
      'en': 'Yes',
      'ar': 'نعم',
      'de': 'Ja',
      'es': 'Sí',
      'fr': 'Oui',
      'hi': 'हाँ',
      'ja': 'はい',
      'pt': 'Sim',
      'ru': 'Да',
      'zh_Hans': '是的',
    },
  },
  // Miscellaneous
  {
    'eejc40ri': {
      'en': 'Please allow camera access.',
      'ar': 'يرجى السماح بالوصول للكاميرا.',
      'de': 'Bitte erlauben Sie den Kamerazugriff.',
      'es': 'Por favor permita el acceso a la cámara.',
      'fr': 'Veuillez autoriser l\'accès à la caméra.',
      'hi': 'कृपया कैमरे तक पहुंच की अनुमति दें.',
      'ja': 'カメラへのアクセスを許可してください。',
      'pt': 'Por favor, permita o acesso à câmera.',
      'ru': 'Пожалуйста, разрешите доступ к камере.',
      'zh_Hans': '请允许相机访问。',
    },
    'kk3f7drw': {
      'en': 'Pelase allow camera access.',
      'ar': 'يرجى السماح بالوصول إلى الكاميرا.',
      'de': 'Bitte erlauben Sie den Kamerazugriff.',
      'es': 'Por favor permita el acceso a la cámara.',
      'fr': 'Veuillez autoriser l\'accès à la caméra.',
      'hi': 'कृपया कैमरा एक्सेस की अनुमति दें।',
      'ja': 'カメラへのアクセスを許可してください。',
      'pt': 'Pelase permite acesso à câmera.',
      'ru': 'Пожалуйста, разрешите доступ к камере.',
      'zh_Hans': '请允许相机访问。',
    },
    'bwgjtvli': {
      'en': 'Please allow mic to record audio.',
      'ar': 'يرجى السماح للميكروفون بتسجيل الصوت.',
      'de': 'Bitte erlauben Sie dem Mikrofon, Audio aufzunehmen.',
      'es': 'Permita que el micrófono grabe audio.',
      'fr': 'Veuillez autoriser le micro à enregistrer l\'audio.',
      'hi': 'कृपया माइक को ऑडियो रिकॉर्ड करने की अनुमति दें।',
      'ja': 'マイクが音声を録音できるようにしてください。',
      'pt': 'Por favor, permita que o microfone grave áudio.',
      'ru': 'Пожалуйста, разрешите микрофону записывать звук.',
      'zh_Hans': '请允许麦克风录制音频。',
    },
    'iudxmqhv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '4v3l3lbm': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'euv4ceki': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'x2gsj4zf': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'qrimfk4v': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'n7ec8ecf': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ygsqx97b': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'h1jp8zo8': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '0uy3v7tg': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5b56hh2e': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'f26pxjzf': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'my5217qk': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'j0kpfl2s': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'mv9b2zjq': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'ipilhrld': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'x3tlz5wn': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'wmpvteyb': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'guqz8bo9': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'dxf7zwt2': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    's4ur8l4y': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'xs5ta9is': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    '5qad7715': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'n8t4vonx': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'fm0xsscd': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
    'o0obn276': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'pt': '',
      'ru': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
